import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Form, Button } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Electa</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className={styles.main}>
        <div className={styles.loginContainer}>
          <Form className={'form'}>
            <Form.Group
              className={styles.emailContainer}
              controlId='formBasicEmail'
            >
              <Form.Label>Email address</Form.Label>
              <Form.Control type='email' placeholder='Enter email' />
              <Form.Text className='neverShare'>
                We'll never share your email with anyone else.
              </Form.Text>
            </Form.Group>

            <Form.Group className='passContainer' controlId='formBasicPassword'>
              <Form.Label>Password</Form.Label>
              <Form.Control type='password' placeholder='Password' />
            </Form.Group>

            <Form.Group className='passFormGroup' controlId='formBasicCheckbox'>
              <Form.Check type='checkbox' label='Remember Password' />
            </Form.Group>

            <Button variant='primary' type='submit'>
              Submit
            </Button>
          </Form>
        </div>
      </main>
    </div>
  )
}
